// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLx4OSdFf0ikn51Aw383VZ9uRuriQiCF8',
    appId: '1:366686886508:web:1fb8a5844e1e1f0675d649',
    messagingSenderId: '366686886508',
    projectId: 'todoapp-3ea7b',
    authDomain: 'todoapp-3ea7b.firebaseapp.com',
    storageBucket: 'todoapp-3ea7b.firebasestorage.app',
    measurementId: 'G-KFSHSJKKCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXsZWlDWrs01HEMUZ_WQ5ZA8Jb-6swJtk',
    appId: '1:366686886508:android:47e6b16769f3f08175d649',
    messagingSenderId: '366686886508',
    projectId: 'todoapp-3ea7b',
    storageBucket: 'todoapp-3ea7b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLx4OSdFf0ikn51Aw383VZ9uRuriQiCF8',
    appId: '1:366686886508:web:513331b699cdfd9a75d649',
    messagingSenderId: '366686886508',
    projectId: 'todoapp-3ea7b',
    authDomain: 'todoapp-3ea7b.firebaseapp.com',
    storageBucket: 'todoapp-3ea7b.firebasestorage.app',
    measurementId: 'G-CZ5RJ8K6CJ',
  );
}
